version: '3'

services:
  db:
    container_name: health-API
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: healthForSickness
    ports:
      - "3306:3306"
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
